using System.ComponentModel.DataAnnotations;

namespace EventManagement.Models
{
    /// <summary>
    /// Represents a community event in the system.
    /// Linked to the authenticated user who created it.
    /// </summary>
    public class Event
    {
        // Primary key — auto-generated by EF Core
        public int Id { get; set; }

        /// <summary>Short title displayed in the event list.</summary>
        [Required(ErrorMessage = "Title is required.")]
        [StringLength(100, ErrorMessage = "Title cannot exceed 100 characters.")]
        [Display(Name = "Event Title")]
        public string Title { get; set; } = string.Empty;

        /// <summary>Full description of the event.</summary>
        [Required(ErrorMessage = "Description is required.")]
        [Display(Name = "Description")]
        public string Description { get; set; } = string.Empty;

        /// <summary>Date the event takes place.</summary>
        [Required(ErrorMessage = "Date is required.")]
        [DataType(DataType.Date)]
        [Display(Name = "Event Date")]
        public DateTime Date { get; set; }

        /// <summary>Time the event starts.</summary>
        [Required(ErrorMessage = "Time is required.")]
        [DataType(DataType.Time)]
        [Display(Name = "Start Time")]
        public TimeSpan Time { get; set; }

        /// <summary>Physical or virtual location of the event.</summary>
        [Required(ErrorMessage = "Location is required.")]
        [StringLength(200, ErrorMessage = "Location cannot exceed 200 characters.")]
        [Display(Name = "Location")]
        public string Location { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key linking the event to the user who created it.
        /// Set automatically by the controller; not displayed in forms.
        /// </summary>
        public string? UserId { get; set; }
    }
}
